import type { Metadata } from "next";
import localFont from "next/font/local";
import React from 'react';
import ReactQueryProvider from "./utils/providers/ReactQueryProvider";
import { headers } from 'next/headers'
import "./globals.css";
import FairfieldHeader from "./components/fairfieldbusinesslistings/Header";
import FairfieldFooter from "./components/fairfieldbusinesslistings/Footer";
import IowaCityHeader from "./components/iowacitybusinessesforsale/Header";
import IowaCityFooter from "./components/iowacitybusinessesforsale/Footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

let Header = FairfieldHeader;
let Footer = FairfieldFooter;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const host = headers().get('x-custom-host') || '';

  console.log("host2", host);

  if (host?.includes('iowacitybusinessesforsale.com')) {
    console.log("over here ");
    Header =  IowaCityHeader;
    Footer = IowaCityFooter;
  }

  return (
      <html lang="en">

      <body
          className="text-forground-light bg-white"
      >
      <ReactQueryProvider>
          <Header/>
          <div className="min-h-[calc(100vh-189px)] md:min-h-[calc(100vh-260px)]">
              {children}
          </div>
          <Footer/>
      </ReactQueryProvider>
      </body>
      </html>
  );
}
